weather fetcher code and test with example region
Ques-Study/WeatherCalendarServer pull request #13
Opened 2017-07-29 18:16 UTC by DonghyunNa

- Use restler module to make request to api server
- Use xml2json to make json from xml
- Pass should test

2017-07-30 01:40 UTC, crowjdh commented
### Some suggestions: ###
- Capitalize the first character of the name of PR.
- Add yourself as assignee.(It's under the "Reviewers" section)
- What do you think about changing name of the weather fetcher module to "weather-api"? Because
```javascript
weather-fetcher.fetch();
```
seems redundant to me.
- Add line below to your PR comment to close issue that you're assigned
```
This changes resolves #8.
```

### Questions ###
- I'm not sure about what your comment "Pass should test" exactly means. You mean "Should pass test"?

2017-07-30 01:42 UTC, crowjdh requested changes
I specified some issues to resolve. Please take your time to resolve :)

2017-07-30 01:42 UTC, crowjdh commented on models/weather-fetcher.js
> +
I think this breakline shouldn't be here :)

2017-07-30 01:42 UTC, crowjdh commented on models/weather-fetcher.js
> +}
Missing newline at the end of file

2017-07-30 01:42 UTC, crowjdh commented on models/weather-fetcher.js
> +        var result = {};
This resule dictionary is redundant and should be removed

2017-07-30 01:42 UTC, crowjdh commented on tests/weather-fetcher.spec.js
> +});
New line here too :)

2017-07-30 01:42 UTC, crowjdh commented on tests/weather-fetcher.spec.js
> +        should.exist(data);
This line should be placed before retrieving value from dictionary

2017-07-30 01:42 UTC, crowjdh commented on tests/weather-fetcher.spec.js
> +        var items = data["rss"]["channel"]["item"]["description"]["body"]["data"];
I'm not sure what is data and items. Can you give more meaningful names to these variables?

2017-07-30 01:42 UTC, crowjdh commented on models/weather-fetcher.js
> +        rest.get('http://www.kma.go.kr/wid/queryDFSRSS.jsp?zone=2723067100')
I think the zone code(2723067100 in this case) should be passed as a parameter of this funtion.

2017-07-31 08:09 UTC, DonghyunNa commented on models/weather-fetcher.js
> +        rest.get('http://www.kma.go.kr/wid/queryDFSRSS.jsp?zone=2723067100')
지금은 기본값만 넣어두고 차후에 parameter 받아서 지역별로 데이터 받아와야 합니다.

2017-07-31 08:22 UTC, crowjdh approved these changes

2017-07-31 08:23 UTC, yeareater approved these changes

2017-07-31 08:24 UTC, merged