Mongodb setup
Ques-Study/WeatherCalendarServer pull request #14
Opened 2017-07-31 10:16 UTC by Frownii

Create weather schema and test insert/retrieve.
This resolves #9.

2017-07-31 18:29 UTC, DonghyunNa approved these changes

2017-08-01 02:24 UTC, crowjdh requested changes
I left some issues(including suggestions). Please check and consider updating :)

2017-08-01 02:24 UTC, crowjdh commented on tests/mongodb.spec.js
> +        console.log("dropped.");
I forgot to remove this log which looks unnecessary. Maybe we can omit callback function entirely.

2017-08-01 02:24 UTC, crowjdh commented on models/weatherSchema.js
> +  maxTem : String,
I wonder why these two fields are declaired as string. Can you give me some explanation?

2017-08-01 02:24 UTC, crowjdh commented on tests/mongodb.spec.js
> +const dailyWeathers = require("../models/weatherSchema");
I think the name of the model(class) should start with capital letter.
Check out the link below and consider changing it :)

Reference: [Mongoose Schemas v4.11.5](http://mongoosejs.com/docs/guide.html)

2017-08-01 02:24 UTC, crowjdh commented on tests/mongodb.spec.js
> +      }
How about refactoring if-else statement into something like below:

```javascript
// Below is psudocode, so you should check javascript syntax and run test.
should.not.exist(err);
done();
```

2017-08-01 02:24 UTC, crowjdh commented on tests/mongodb.spec.js
> +const dailyWeathers = require("../models/weatherSchema");
Also, I think the name of the class should be "Weather", whichis more general then "DailyWeather".

2017-08-04 06:39 UTC, Frownii commented on models/weatherSchema.js
> +  maxTem : String,
I thought the weather data include strings like ℃ or m/s or etc.
I checked it doesn't.

2017-08-05 02:20 UTC, crowjdh approved these changes
Great work!

2017-08-05 02:20 UTC, merged