Create weather-updating module
Ques-Study/WeatherCalendarServer pull request #20
Opened 2017-09-04 13:17 UTC by Frownii

Create module and test insert/update.
This resolves #17

2017-09-04 13:28 UTC, DonghyunNa requested changes
need same type of indent in your code

2017-09-04 13:28 UTC, DonghyunNa commented on tests/weather.updater.spec.js
> +function checkWeathersHaveProperties (weathersArray) {
need unified indent

2017-09-05 05:31 UTC, crowjdh requested changes
Great job :)
I left some minor(?) improvements you can apply.

Also, consider removing "console.log"s where they're unnecessary.

2017-09-05 05:31 UTC, crowjdh commented on models/weatherUpdater.js
> +module.exports.updateWeather = function(weathers) {
How about changing name of the function into **saveWeathers** and the file name into **weather-utils**?

2017-09-05 05:31 UTC, crowjdh commented on models/weatherUpdater.js
> +function updateWeather(dailyWeather, callback) {
This function performs *save&update* at the same time. How about changing name of the function into **saveOrUpdateWeather**?

2017-09-05 05:31 UTC, crowjdh commented on models/weatherUpdater.js
> +function saveNewDailyWeathers(newDailyWeather, callback) {
Suggestions:
- function saveWeather(weather, callback) { ... }

2017-09-05 05:31 UTC, crowjdh commented on models/weatherUpdater.js
> +function updateHourlyWeather(oldWeather, newWeather, callback) {
I think the name of the function can be **updateWeather**.

2017-09-05 05:31 UTC, crowjdh commented on tests/weather.updater.spec.js
> +
Redundant new line here :)

2017-09-05 05:31 UTC, crowjdh commented on tests/weather.updater.spec.js
> +		});
Lines at 44~54 should be:
```javascript
weatherUtil.saveWeathers([firstWeather]).then(function(err) {
    should.not.exist(err);
    return weatherUtil.saveWeathers([secondWeather]);
}).then(function(err) {
    should.not.exist(err);
    Weather.findOne({ date: firstWeather.date }, function(err, updatedWeather) {
        should.not.exist(err);
        assertEquals(updatedWeather, weather);
        done();
    });
});
```

2017-09-05 05:31 UTC, crowjdh commented on tests/weather.updater.spec.js
> +function compare(lhs, rhs) {
Changing name of this function into **assertEquals** seems better :)

2017-09-05 05:36 UTC, crowjdh commented
Also, feel free to comment to my reviews if it doesn't seem legitimate.(Doubt everything!!)

2017-09-06 03:18 UTC, crowjdh approved these changes

2017-09-06 09:23 UTC, DonghyunNa approved these changes
good

2017-09-06 09:23 UTC, merged